# Generated by Django 5.0.7 on 2024-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_questionattemptdetails_quiz_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattemptdetails',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
